### ISSUE TITLE
Only for Linux?

### ISSUE THREAD

**Issue by troelssiggaard** [phreed/ts-typings#1]
Trying to NPM install your **cytoscape typings** I get an "Unsupported platform" error because you've defined Linux as the OS. I'm on a MacOS system. 

Could you update your package.json file with "any" or just remove the OS definition from the package.json file?

Best, Troels

**Comment by awaidmann** [comment]
I agree with @troelssiggaard. For the time being I'm going to fork this repo and point my `package.json` at it. But you're still saving me a hell of a lot of time so thank you.

**Comment by phreed** [comment]
Sorry for the delay in merging, it is now done.
